# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name AbilityTags

const VALUES: Array[String] = [
	"ability_tag_skill",
	"ability_tag_primary",
	"ability_tag_damage",
	"ability_tag_activating",
	"ability_tag_silenced",
]

const ABILITY_TAG_SKILL: String = "ability_tag_skill"
const ABILITY_TAG_PRIMARY: String = "ability_tag_primary"
const ABILITY_TAG_DAMAGE: String = "ability_tag_damage"
const ABILITY_TAG_ACTIVATING: String = "ability_tag_activating"
const ABILITY_TAG_SILENCED: String = "ability_tag_silenced"
