# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name Actions

const VALUES: Array[String] = [
	"move_up",
	"move_down",
	"move_left",
	"move_right",
	"aim_up",
	"aim_down",
	"aim_left",
	"aim_right",
	"use_active_item",
	"pause",
	"debug_toggle_replay",
]

const MOVE_UP: String = "move_up"
const MOVE_DOWN: String = "move_down"
const MOVE_LEFT: String = "move_left"
const MOVE_RIGHT: String = "move_right"
const AIM_UP: String = "aim_up"
const AIM_DOWN: String = "aim_down"
const AIM_LEFT: String = "aim_left"
const AIM_RIGHT: String = "aim_right"
const USE_ACTIVE_ITEM: String = "use_active_item"
const PAUSE: String = "pause"
const DEBUG_TOGGLE_REPLAY: String = "debug_toggle_replay"
