# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name Actions

const VALUES: Array[String] = [
	"move",
	"aim",
	"pointer_position",
	"fire",
	"reload",
	"skill_1",
	"skill_2",
	"skill_3",
	"skill_4",
	"dash",
	"interact",
	"show_stats_panel",
	"pause",
	"ui_up",
	"ui_down",
	"ui_left",
	"ui_right",
	"ui_confirm",
	"ui_back",
	"debug_toggle_console",
	"debug_submit_command",
	"debug_close_console",
	"debug_toggle_replay",
]

const MOVE: String = "move"
const AIM: String = "aim"
const POINTER_POSITION: String = "pointer_position"
const FIRE: String = "fire"
const RELOAD: String = "reload"
const SKILL_1: String = "skill_1"
const SKILL_2: String = "skill_2"
const SKILL_3: String = "skill_3"
const SKILL_4: String = "skill_4"
const DASH: String = "dash"
const INTERACT: String = "interact"
const SHOW_STATS_PANEL: String = "show_stats_panel"
const PAUSE: String = "pause"
const UI_UP: String = "ui_up"
const UI_DOWN: String = "ui_down"
const UI_LEFT: String = "ui_left"
const UI_RIGHT: String = "ui_right"
const UI_CONFIRM: String = "ui_confirm"
const UI_BACK: String = "ui_back"
const DEBUG_TOGGLE_CONSOLE: String = "debug_toggle_console"
const DEBUG_SUBMIT_COMMAND: String = "debug_submit_command"
const DEBUG_CLOSE_CONSOLE: String = "debug_close_console"
const DEBUG_TOGGLE_REPLAY: String = "debug_toggle_replay"
