# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name AnalyticsEvents

const VALUES: Array[String] = [
	"run_start",
	"run_end",
	"player_death",
	"level_up",
	"relic_pick",
	"item_use",
	"wave_milestone",
	"game_pause",
	"game_resume",
	"replay_recorded",
	"replay_replay_diff",
	"state_changed",
	"save_written",
	"save_loaded",
	"save_deleted",
	"save_migrated",
	"save_corrupted",
	"run_suspended",
	"run_resumed",
	"pool_overflow",
]

const RUN_START: String = "run_start"
const RUN_END: String = "run_end"
const PLAYER_DEATH: String = "player_death"
const LEVEL_UP: String = "level_up"
const RELIC_PICK: String = "relic_pick"
const ITEM_USE: String = "item_use"
const WAVE_MILESTONE: String = "wave_milestone"
const GAME_PAUSE: String = "game_pause"
const GAME_RESUME: String = "game_resume"
const REPLAY_RECORDED: String = "replay_recorded"
const REPLAY_REPLAY_DIFF: String = "replay_replay_diff"
const STATE_CHANGED: String = "state_changed"
const SAVE_WRITTEN: String = "save_written"
const SAVE_LOADED: String = "save_loaded"
const SAVE_DELETED: String = "save_deleted"
const SAVE_MIGRATED: String = "save_migrated"
const SAVE_CORRUPTED: String = "save_corrupted"
const RUN_SUSPENDED: String = "run_suspended"
const RUN_RESUMED: String = "run_resumed"
const POOL_OVERFLOW: String = "pool_overflow"
