# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name AudioIds

const PREFIXES: Array[String] = [
	"sfx_player_",
	"sfx_enemy_",
	"sfx_pickup_",
	"sfx_ui_",
	"music_",
	"voice_",
]

const SFX_PLAYER_PREFIX: String = "sfx_player_"
const SFX_ENEMY_PREFIX: String = "sfx_enemy_"
const SFX_PICKUP_PREFIX: String = "sfx_pickup_"
const SFX_UI_PREFIX: String = "sfx_ui_"
const MUSIC_PREFIX: String = "music_"
const VOICE_PREFIX: String = "voice_"
