# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name Capabilities

const VALUES: Array[String] = [
	"cap_aim_mode_override",
	"cap_fire_mode_override",
	"cap_movement_model_override",
	"cap_inventory_slot_override",
	"cap_camera_policy_override",
]

const CAP_AIM_MODE_OVERRIDE: String = "cap_aim_mode_override"
const CAP_FIRE_MODE_OVERRIDE: String = "cap_fire_mode_override"
const CAP_MOVEMENT_MODEL_OVERRIDE: String = "cap_movement_model_override"
const CAP_INVENTORY_SLOT_OVERRIDE: String = "cap_inventory_slot_override"
const CAP_CAMERA_POLICY_OVERRIDE: String = "cap_camera_policy_override"
