# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name CharacterIds

const VALUES: Array[String] = [
	"character_default",
]

const CHARACTER_DEFAULT: String = "character_default"
