# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name CharacterIds

const VALUES: Array[String] = [
	"character_primary_a",
	"character_primary_b",
]

const CHARACTER_PRIMARY_A: String = "character_primary_a"
const CHARACTER_PRIMARY_B: String = "character_primary_b"
