# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name ContentTags

const VALUES: Array[String] = [
	"tag_character",
	"tag_enemy",
	"tag_relic",
	"tag_active_item",
	"tag_consumable",
	"tag_limit_break",
]

const TAG_CHARACTER: String = "tag_character"
const TAG_ENEMY: String = "tag_enemy"
const TAG_RELIC: String = "tag_relic"
const TAG_ACTIVE_ITEM: String = "tag_active_item"
const TAG_CONSUMABLE: String = "tag_consumable"
const TAG_LIMIT_BREAK: String = "tag_limit_break"
