# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name ContentUnlockRuleModes

const VALUES: Array[String] = [
	"all",
	"any",
]

const ALL: String = "all"
const ANY: String = "any"
