# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name ContentUnlockProgressCounters

const VALUES: Array[String] = [
	"runs_ended",
	"runs_completed",
	"character_run_completed",
	"enemy_defeated_total",
	"enemy_defeated",
]

const RUNS_ENDED: String = "runs_ended"
const RUNS_COMPLETED: String = "runs_completed"
const CHARACTER_RUN_COMPLETED: String = "character_run_completed"
const ENEMY_DEFEATED_TOTAL: String = "enemy_defeated_total"
const ENEMY_DEFEATED: String = "enemy_defeated"
