# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name ContentUnlockTypes

const VALUES: Array[String] = [
	"character",
	"gear_mod",
	"enemy",
]

const CHARACTER: String = "character"
const GEAR_MOD: String = "gear_mod"
const ENEMY: String = "enemy"
