# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name DamageTypes

const VALUES: Array[String] = [
	"physical",
	"fire",
	"poison",
	"lightning",
	"true",
]

const PHYSICAL: String = "physical"
const FIRE: String = "fire"
const POISON: String = "poison"
const LIGHTNING: String = "lightning"
const ID_TRUE: String = "true"
