# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name DamageTargetGroups

const VALUES: Array[String] = [
	"active_enemies",
	"active_interest_point_targets",
	"active_projectile_blockers",
	"active_player",
	"active_deployables",
	"active_world_event_defense_targets",
]

const ACTIVE_ENEMIES: String = "active_enemies"
const ACTIVE_INTEREST_POINT_TARGETS: String = "active_interest_point_targets"
const ACTIVE_PROJECTILE_BLOCKERS: String = "active_projectile_blockers"
const ACTIVE_PLAYER: String = "active_player"
const ACTIVE_DEPLOYABLES: String = "active_deployables"
const ACTIVE_WORLD_EVENT_DEFENSE_TARGETS: String = "active_world_event_defense_targets"
