# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name DoorUnlockRules

const VALUES: Array[String] = [
	"unlock_on_clear",
	"unlock_open",
]

const UNLOCK_ON_CLEAR: String = "unlock_on_clear"
const UNLOCK_OPEN: String = "unlock_open"
