# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name DoorDirections

const VALUES: Array[String] = [
	"dir_north",
	"dir_south",
	"dir_east",
	"dir_west",
]

const DIR_NORTH: String = "dir_north"
const DIR_SOUTH: String = "dir_south"
const DIR_EAST: String = "dir_east"
const DIR_WEST: String = "dir_west"
