# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name EffectActions

const VALUES: Array[String] = [
	"damage",
	"apply_status",
	"temporary_modifier",
	"heal",
	"grant_shield",
	"grant_overshield",
	"grant_gold",
	"spawn_projectile",
	"spawn_enemy",
	"spawn_barrier",
]

const DAMAGE: String = "damage"
const APPLY_STATUS: String = "apply_status"
const TEMPORARY_MODIFIER: String = "temporary_modifier"
const HEAL: String = "heal"
const GRANT_SHIELD: String = "grant_shield"
const GRANT_OVERSHIELD: String = "grant_overshield"
const GRANT_GOLD: String = "grant_gold"
const SPAWN_PROJECTILE: String = "spawn_projectile"
const SPAWN_ENEMY: String = "spawn_enemy"
const SPAWN_BARRIER: String = "spawn_barrier"
