# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name Effects

const VALUES: Array[String] = [
	"pierce",
	"split",
	"homing",
	"ignite",
	"chain",
	"knockback",
	"explode",
	"lifesteal",
]

const PIERCE: String = "pierce"
const SPLIT: String = "split"
const HOMING: String = "homing"
const IGNITE: String = "ignite"
const CHAIN: String = "chain"
const KNOCKBACK: String = "knockback"
const EXPLODE: String = "explode"
const LIFESTEAL: String = "lifesteal"
