# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name EffectConditions

const VALUES: Array[String] = [
	"team",
	"element",
	"damage_flag",
	"actor_tag",
	"health_ratio",
	"board_cell_relation",
	"module_relation",
]

const TEAM: String = "team"
const ELEMENT: String = "element"
const DAMAGE_FLAG: String = "damage_flag"
const ACTOR_TAG: String = "actor_tag"
const HEALTH_RATIO: String = "health_ratio"
const BOARD_CELL_RELATION: String = "board_cell_relation"
const MODULE_RELATION: String = "module_relation"
