# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name EffectTriggers

const VALUES: Array[String] = [
	"skill_activated",
	"damage_dealt",
	"kill",
	"damage_taken",
	"dash",
	"module_entered",
	"interval",
]

const SKILL_ACTIVATED: String = "skill_activated"
const DAMAGE_DEALT: String = "damage_dealt"
const KILL: String = "kill"
const DAMAGE_TAKEN: String = "damage_taken"
const DASH: String = "dash"
const MODULE_ENTERED: String = "module_entered"
const INTERVAL: String = "interval"
