# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name Elements

const VALUES: Array[String] = [
	"element_neutral",
	"element_primary_a",
	"element_primary_b",
	"element_primary_c",
	"element_composite_ab",
	"element_composite_bc",
	"element_composite_ca",
]

const ELEMENT_NEUTRAL: String = "element_neutral"
const ELEMENT_PRIMARY_A: String = "element_primary_a"
const ELEMENT_PRIMARY_B: String = "element_primary_b"
const ELEMENT_PRIMARY_C: String = "element_primary_c"
const ELEMENT_COMPOSITE_AB: String = "element_composite_ab"
const ELEMENT_COMPOSITE_BC: String = "element_composite_bc"
const ELEMENT_COMPOSITE_CA: String = "element_composite_ca"
