# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name EnemyAiActions

const VALUES: Array[String] = [
	"ai_action_approach_target",
	"ai_action_flee_threat",
	"ai_action_orbit_target",
	"ai_action_charge_target",
	"ai_action_guard_home",
]

const AI_ACTION_APPROACH_TARGET: String = "ai_action_approach_target"
const AI_ACTION_FLEE_THREAT: String = "ai_action_flee_threat"
const AI_ACTION_ORBIT_TARGET: String = "ai_action_orbit_target"
const AI_ACTION_CHARGE_TARGET: String = "ai_action_charge_target"
const AI_ACTION_GUARD_HOME: String = "ai_action_guard_home"
