# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name EnemyDefeatCauses

const VALUES: Array[String] = [
	"player_damage",
	"enemy_explosion",
	"exploder_detonation",
	"other_cause",
]

const PLAYER_DAMAGE: String = "player_damage"
const ENEMY_EXPLOSION: String = "enemy_explosion"
const EXPLODER_DETONATION: String = "exploder_detonation"
const OTHER_CAUSE: String = "other_cause"
