# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name Events

const VALUES: Array[String] = [
	"on_fire",
	"on_hit",
	"on_kill",
	"on_player_hit",
	"on_level_up",
	"on_pickup",
	"on_tick",
]

const ON_FIRE: String = "on_fire"
const ON_HIT: String = "on_hit"
const ON_KILL: String = "on_kill"
const ON_PLAYER_HIT: String = "on_player_hit"
const ON_LEVEL_UP: String = "on_level_up"
const ON_PICKUP: String = "on_pickup"
const ON_TICK: String = "on_tick"
