# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name GameModes

const VALUES: Array[String] = [
	"mode_standard_survival",
]

const MODE_STANDARD_SURVIVAL: String = "mode_standard_survival"
