# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name GearModPlacementOutcomes

const VALUES: Array[String] = [
	"placed",
	"cancelled",
]

const PLACED: String = "placed"
const CANCELLED: String = "cancelled"
