# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name GearModIds

const VALUES: Array[String] = [
	"gear_mod_weapon_damage_test",
]

const GEAR_MOD_WEAPON_DAMAGE_TEST: String = "gear_mod_weapon_damage_test"
