# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name GearModMapBehaviors

const VALUES: Array[String] = [
	"periodic_enemy_spawn",
]

const PERIODIC_ENEMY_SPAWN: String = "periodic_enemy_spawn"
