# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name GearModSlots

const VALUES: Array[String] = [
	"hero",
	"weapon",
]

const HERO: String = "hero"
const WEAPON: String = "weapon"
