# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name GearModStackRules

const VALUES: Array[String] = [
	"unique_by_id",
]

const UNIQUE_BY_ID: String = "unique_by_id"
