# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name GearModKinds

const VALUES: Array[String] = [
	"effect",
	"map",
	"grid",
]

const EFFECT: String = "effect"
const MAP: String = "map"
const GRID: String = "grid"
