# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name GearModResources

const VALUES: Array[String] = [
	"gear_mod_dust",
]

const GEAR_MOD_DUST: String = "gear_mod_dust"
