# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name GearModComponentTypes

const VALUES: Array[String] = [
	"modifier",
	"program",
	"board_rule",
]

const MODIFIER: String = "modifier"
const PROGRAM: String = "program"
const BOARD_RULE: String = "board_rule"
