# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name GoldTransactionReasons

const VALUES: Array[String] = [
	"enemy_drop",
	"event_reward",
	"event_cost",
	"gear_mod_overflow",
	"debug_command",
]

const ENEMY_DROP: String = "enemy_drop"
const EVENT_REWARD: String = "event_reward"
const EVENT_COST: String = "event_cost"
const GEAR_MOD_OVERFLOW: String = "gear_mod_overflow"
const DEBUG_COMMAND: String = "debug_command"
