# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name HeroPassiveIds

const VALUES: Array[String] = [
	"passive_primary_a_guard",
	"passive_primary_b_guard",
]

const PASSIVE_PRIMARY_A_GUARD: String = "passive_primary_a_guard"
const PASSIVE_PRIMARY_B_GUARD: String = "passive_primary_b_guard"
