# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name InputBindingIds

const VALUES: Array[String] = [
	"input.move_up",
	"input.move_down",
	"input.move_left",
	"input.move_right",
	"input.move_stick",
	"input.aim_up",
	"input.aim_down",
	"input.aim_left",
	"input.aim_right",
	"input.aim_stick",
	"input.fire",
	"input.use_active_item",
	"input.interact",
	"input.show_stats_panel",
	"input.pause",
	"input.ui_confirm",
	"input.ui_back",
]

const INPUT_MOVE_UP: String = "input.move_up"
const INPUT_MOVE_DOWN: String = "input.move_down"
const INPUT_MOVE_LEFT: String = "input.move_left"
const INPUT_MOVE_RIGHT: String = "input.move_right"
const INPUT_MOVE_STICK: String = "input.move_stick"
const INPUT_AIM_UP: String = "input.aim_up"
const INPUT_AIM_DOWN: String = "input.aim_down"
const INPUT_AIM_LEFT: String = "input.aim_left"
const INPUT_AIM_RIGHT: String = "input.aim_right"
const INPUT_AIM_STICK: String = "input.aim_stick"
const INPUT_FIRE: String = "input.fire"
const INPUT_USE_ACTIVE_ITEM: String = "input.use_active_item"
const INPUT_INTERACT: String = "input.interact"
const INPUT_SHOW_STATS_PANEL: String = "input.show_stats_panel"
const INPUT_PAUSE: String = "input.pause"
const INPUT_UI_CONFIRM: String = "input.ui_confirm"
const INPUT_UI_BACK: String = "input.ui_back"
