# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name MetaUnlocks

const UNLOCK_KINDS: Array[String] = [
	"character",
	"relic_pool",
	"mode",
	"difficulty_tier",
	"run_start_option",
]

const UNLOCK_IDS: Array[String] = [
	"unlock_character_default",
	"unlock_relic_pool_basic",
	"unlock_challenge_room",
	"unlock_difficulty_tier_2",
	"unlock_starting_relic_choice_1",
	"unlock_starting_relic_choice_2",
	"unlock_starting_relic_choice_3",
]

const KIND_CHARACTER: String = "character"
const KIND_RELIC_POOL: String = "relic_pool"
const KIND_MODE: String = "mode"
const KIND_DIFFICULTY_TIER: String = "difficulty_tier"
const KIND_RUN_START_OPTION: String = "run_start_option"
const UNLOCK_CHARACTER_DEFAULT: String = "unlock_character_default"
const UNLOCK_RELIC_POOL_BASIC: String = "unlock_relic_pool_basic"
const UNLOCK_CHALLENGE_ROOM: String = "unlock_challenge_room"
const UNLOCK_DIFFICULTY_TIER_2: String = "unlock_difficulty_tier_2"
const UNLOCK_STARTING_RELIC_CHOICE_1: String = "unlock_starting_relic_choice_1"
const UNLOCK_STARTING_RELIC_CHOICE_2: String = "unlock_starting_relic_choice_2"
const UNLOCK_STARTING_RELIC_CHOICE_3: String = "unlock_starting_relic_choice_3"
