# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name MetaUpgrades

const VALUES: Array[String] = [
	"meta_upgrade_max_hp",
	"meta_upgrade_damage",
	"meta_upgrade_move_speed",
	"meta_upgrade_pickup_range",
	"meta_upgrade_luck",
	"meta_upgrade_starter_choice",
]

const META_UPGRADE_MAX_HP: String = "meta_upgrade_max_hp"
const META_UPGRADE_DAMAGE: String = "meta_upgrade_damage"
const META_UPGRADE_MOVE_SPEED: String = "meta_upgrade_move_speed"
const META_UPGRADE_PICKUP_RANGE: String = "meta_upgrade_pickup_range"
const META_UPGRADE_LUCK: String = "meta_upgrade_luck"
const META_UPGRADE_STARTER_CHOICE: String = "meta_upgrade_starter_choice"
