# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name ModuleCellTokens

const VALUES: Array[String] = [
	"module_cell_floor",
	"module_cell_blocked",
]

const MODULE_CELL_FLOOR: String = "module_cell_floor"
const MODULE_CELL_BLOCKED: String = "module_cell_blocked"
