# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name ModuleReviewStatuses

const VALUES: Array[String] = [
	"module_review_candidate",
	"module_review_approved",
]

const MODULE_REVIEW_CANDIDATE: String = "module_review_candidate"
const MODULE_REVIEW_APPROVED: String = "module_review_approved"
