# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name ModuleRoles

const VALUES: Array[String] = [
	"module_role_start",
	"module_role_connector",
	"module_role_combat",
	"module_role_resource",
	"module_role_hazard",
	"module_role_objective",
	"module_role_extraction",
	"module_role_sealed",
]

const MODULE_ROLE_START: String = "module_role_start"
const MODULE_ROLE_CONNECTOR: String = "module_role_connector"
const MODULE_ROLE_COMBAT: String = "module_role_combat"
const MODULE_ROLE_RESOURCE: String = "module_role_resource"
const MODULE_ROLE_HAZARD: String = "module_role_hazard"
const MODULE_ROLE_OBJECTIVE: String = "module_role_objective"
const MODULE_ROLE_EXTRACTION: String = "module_role_extraction"
const MODULE_ROLE_SEALED: String = "module_role_sealed"
