# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name ModuleEdgeDirections

const VALUES: Array[String] = [
	"edge_north",
	"edge_south",
	"edge_east",
	"edge_west",
]

const EDGE_NORTH: String = "edge_north"
const EDGE_SOUTH: String = "edge_south"
const EDGE_EAST: String = "edge_east"
const EDGE_WEST: String = "edge_west"
