# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name ModulePlacementTypes

const VALUES: Array[String] = [
	"module_place_player_start",
	"module_place_enemy_spawn",
	"module_place_hazard",
	"module_place_reward_cache",
	"module_place_objective",
	"module_place_extraction",
]

const MODULE_PLACE_PLAYER_START: String = "module_place_player_start"
const MODULE_PLACE_ENEMY_SPAWN: String = "module_place_enemy_spawn"
const MODULE_PLACE_HAZARD: String = "module_place_hazard"
const MODULE_PLACE_REWARD_CACHE: String = "module_place_reward_cache"
const MODULE_PLACE_OBJECTIVE: String = "module_place_objective"
const MODULE_PLACE_EXTRACTION: String = "module_place_extraction"
