# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name ModuleTileIds

const VALUES: Array[String] = [
	"module_tile_ground_default",
	"module_tile_obstacle_default",
	"module_tile_decoration_default",
]

const MODULE_TILE_GROUND_DEFAULT: String = "module_tile_ground_default"
const MODULE_TILE_OBSTACLE_DEFAULT: String = "module_tile_obstacle_default"
const MODULE_TILE_DECORATION_DEFAULT: String = "module_tile_decoration_default"
