# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name PoolIds

const VALUES: Array[String] = [
	"bullet_basic",
	"bullet_pierce",
	"enemy_chaser",
	"enemy_swarm",
	"enemy_stalker",
	"enemy_bulwark",
	"enemy_spitter",
	"hazard_spike",
	"damage_number",
	"hit_spark",
	"gold_orb",
	"energy_orb",
	"projectile_barrier",
	"vfx_weapon_muzzle_flash",
]

const BULLET_BASIC: String = "bullet_basic"
const BULLET_PIERCE: String = "bullet_pierce"
const ENEMY_CHASER: String = "enemy_chaser"
const ENEMY_SWARM: String = "enemy_swarm"
const ENEMY_STALKER: String = "enemy_stalker"
const ENEMY_BULWARK: String = "enemy_bulwark"
const ENEMY_SPITTER: String = "enemy_spitter"
const HAZARD_SPIKE: String = "hazard_spike"
const DAMAGE_NUMBER: String = "damage_number"
const HIT_SPARK: String = "hit_spark"
const GOLD_ORB: String = "gold_orb"
const ENERGY_ORB: String = "energy_orb"
const PROJECTILE_BARRIER: String = "projectile_barrier"
const VFX_WEAPON_MUZZLE_FLASH: String = "vfx_weapon_muzzle_flash"
