# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name PoolIds

const VALUES: Array[String] = [
	"bullet_basic",
	"bullet_pierce",
	"enemy_chaser",
	"enemy_ranged",
	"enemy_swarm",
	"damage_number",
	"hit_spark",
	"pickup_orb",
]

const BULLET_BASIC: String = "bullet_basic"
const BULLET_PIERCE: String = "bullet_pierce"
const ENEMY_CHASER: String = "enemy_chaser"
const ENEMY_RANGED: String = "enemy_ranged"
const ENEMY_SWARM: String = "enemy_swarm"
const DAMAGE_NUMBER: String = "damage_number"
const HIT_SPARK: String = "hit_spark"
const PICKUP_ORB: String = "pickup_orb"
