# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name RewardChoiceTriggers

const VALUES: Array[String] = [
	"event_reward",
	"debug_command",
]

const EVENT_REWARD: String = "event_reward"
const DEBUG_COMMAND: String = "debug_command"
