# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name RngStreams

const VALUES: Array[String] = [
	"spawn",
	"drop",
	"combat",
	"camera_fx",
	"ui_choice",
	"world",
	"meta",
]

const SPAWN: String = "spawn"
const DROP: String = "drop"
const COMBAT: String = "combat"
const CAMERA_FX: String = "camera_fx"
const UI_CHOICE: String = "ui_choice"
const WORLD: String = "world"
const META: String = "meta"
