# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name RoomClearConditions

const VALUES: Array[String] = [
	"room_clear_all_enemies",
	"room_clear_none",
]

const ROOM_CLEAR_ALL_ENEMIES: String = "room_clear_all_enemies"
const ROOM_CLEAR_NONE: String = "room_clear_none"
