# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name SaveKinds

const VALUES: Array[String] = [
	"meta",
	"run",
	"replay_index",
]

const META: String = "meta"
const RUN: String = "run"
const REPLAY_INDEX: String = "replay_index"
