# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name SettingsKeys

const VALUES: Array[String] = [
	"general.locale",
	"video.fullscreen",
	"video.vsync",
	"audio.master",
	"audio.music",
	"audio.sfx",
	"gameplay.fire_on_release",
	"gameplay.aim_mode",
	"gameplay.screen_shake",
	"gameplay.pause_on_focus_loss",
	"gameplay.record_replays",
	"privacy.analytics_enabled",
]

const GENERAL_LOCALE: String = "general.locale"
const VIDEO_FULLSCREEN: String = "video.fullscreen"
const VIDEO_VSYNC: String = "video.vsync"
const AUDIO_MASTER: String = "audio.master"
const AUDIO_MUSIC: String = "audio.music"
const AUDIO_SFX: String = "audio.sfx"
const GAMEPLAY_FIRE_ON_RELEASE: String = "gameplay.fire_on_release"
const GAMEPLAY_AIM_MODE: String = "gameplay.aim_mode"
const GAMEPLAY_SCREEN_SHAKE: String = "gameplay.screen_shake"
const GAMEPLAY_PAUSE_ON_FOCUS_LOSS: String = "gameplay.pause_on_focus_loss"
const GAMEPLAY_RECORD_REPLAYS: String = "gameplay.record_replays"
const PRIVACY_ANALYTICS_ENABLED: String = "privacy.analytics_enabled"
