# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name SkillIds

const VALUES: Array[String] = [
	"skill_overdrive_rounds",
]

const SKILL_OVERDRIVE_ROUNDS: String = "skill_overdrive_rounds"
