# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name SkillSlots

const VALUES: Array[String] = [
	"skill_1",
	"skill_2",
	"skill_3",
	"skill_4",
]

const SKILL_1: String = "skill_1"
const SKILL_2: String = "skill_2"
const SKILL_3: String = "skill_3"
const SKILL_4: String = "skill_4"
