# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name SkillEffects

const VALUES: Array[String] = [
	"skill_effect_damage",
	"skill_effect_apply_status",
	"skill_effect_weapon_modifiers",
]

const SKILL_EFFECT_DAMAGE: String = "skill_effect_damage"
const SKILL_EFFECT_APPLY_STATUS: String = "skill_effect_apply_status"
const SKILL_EFFECT_WEAPON_MODIFIERS: String = "skill_effect_weapon_modifiers"
