# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name SkillEffects

const VALUES: Array[String] = [
	"skill_effect_damage",
]

const SKILL_EFFECT_DAMAGE: String = "skill_effect_damage"
