# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name SkillTargeting

const VALUES: Array[String] = [
	"aoe_enemies_around_caster",
	"target_enemy",
	"target_ally",
]

const AOE_ENEMIES_AROUND_CASTER: String = "aoe_enemies_around_caster"
const TARGET_ENEMY: String = "target_enemy"
const TARGET_ALLY: String = "target_ally"
