# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name StatusEffects

const VALUES: Array[String] = [
	"burn",
	"poison",
	"bleed",
	"freeze",
	"slow",
	"haste",
	"vulnerable",
	"mark",
	"silence",
]

const BURN: String = "burn"
const POISON: String = "poison"
const BLEED: String = "bleed"
const FREEZE: String = "freeze"
const SLOW: String = "slow"
const HASTE: String = "haste"
const VULNERABLE: String = "vulnerable"
const MARK: String = "mark"
const SILENCE: String = "silence"
