# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name Stats

const VALUES: Array[String] = [
	"max_hp",
	"move_speed",
	"damage",
	"fire_rate",
	"bullet_speed",
	"bullet_range",
	"bullet_count",
	"pierce_count",
	"crit_chance",
	"crit_mult",
	"pickup_range",
	"luck",
	"armor",
	"resist_fire",
	"resist_poison",
	"resist_lightning",
	"lifesteal_ratio",
]

const MAX_HP: String = "max_hp"
const MOVE_SPEED: String = "move_speed"
const DAMAGE: String = "damage"
const FIRE_RATE: String = "fire_rate"
const BULLET_SPEED: String = "bullet_speed"
const BULLET_RANGE: String = "bullet_range"
const BULLET_COUNT: String = "bullet_count"
const PIERCE_COUNT: String = "pierce_count"
const CRIT_CHANCE: String = "crit_chance"
const CRIT_MULT: String = "crit_mult"
const PICKUP_RANGE: String = "pickup_range"
const LUCK: String = "luck"
const ARMOR: String = "armor"
const RESIST_FIRE: String = "resist_fire"
const RESIST_POISON: String = "resist_poison"
const RESIST_LIGHTNING: String = "resist_lightning"
const LIFESTEAL_RATIO: String = "lifesteal_ratio"
