# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name StatusStackRules

const VALUES: Array[String] = [
	"REPLACE",
	"REFRESH",
	"ADD_DURATION",
	"INDEPENDENT",
	"MAX_MAGNITUDE",
]

const REPLACE: String = "REPLACE"
const REFRESH: String = "REFRESH"
const ADD_DURATION: String = "ADD_DURATION"
const INDEPENDENT: String = "INDEPENDENT"
const MAX_MAGNITUDE: String = "MAX_MAGNITUDE"
