# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name TeleporterNetworkIds

const VALUES: Array[String] = [
	"teleporter_network_primary",
]

const TELEPORTER_NETWORK_PRIMARY: String = "teleporter_network_primary"
