# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name TeleportChoiceOutcomes

const VALUES: Array[String] = [
	"teleported",
	"cancelled",
]

const TELEPORTED: String = "teleported"
const CANCELLED: String = "cancelled"
