# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name VfxDomains

const VALUES: Array[String] = [
	"ui",
	"actor",
	"combat",
	"skill",
	"status",
	"pickup",
	"environment",
	"screen",
]

const UI: String = "ui"
const ACTOR: String = "actor"
const COMBAT: String = "combat"
const SKILL: String = "skill"
const STATUS: String = "status"
const PICKUP: String = "pickup"
const ENVIRONMENT: String = "environment"
const SCREEN: String = "screen"
