# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name VfxAnchors

const VALUES: Array[String] = [
	"center",
	"ground",
	"overhead",
	"status",
	"forward",
	"muzzle",
]

const CENTER: String = "center"
const GROUND: String = "ground"
const OVERHEAD: String = "overhead"
const STATUS: String = "status"
const FORWARD: String = "forward"
const MUZZLE: String = "muzzle"
