# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name VfxKinds

const VALUES: Array[String] = [
	"spawned_scene",
	"target_animation",
	"screen_overlay",
]

const SPAWNED_SCENE: String = "spawned_scene"
const TARGET_ANIMATION: String = "target_animation"
const SCREEN_OVERLAY: String = "screen_overlay"
