# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name VfxCues

const VALUES: Array[String] = [
	"spawn",
	"hurt",
	"hit",
	"defeat",
	"skill_cast",
	"skill_failed",
	"status_applied",
	"status_expired",
	"weapon_fire",
	"modifier_started",
	"modifier_refreshed",
	"modifier_expired",
	"pickup_spawn",
	"pickup_attract",
	"pickup_collect",
	"hazard_telegraph",
	"hazard_activated",
	"ui_enter",
	"ui_exit",
	"ui_focus",
	"ui_press",
	"ui_success",
	"ui_failure",
	"ui_value_increase",
	"ui_value_decrease",
]

const SPAWN: String = "spawn"
const HURT: String = "hurt"
const HIT: String = "hit"
const DEFEAT: String = "defeat"
const SKILL_CAST: String = "skill_cast"
const SKILL_FAILED: String = "skill_failed"
const STATUS_APPLIED: String = "status_applied"
const STATUS_EXPIRED: String = "status_expired"
const WEAPON_FIRE: String = "weapon_fire"
const MODIFIER_STARTED: String = "modifier_started"
const MODIFIER_REFRESHED: String = "modifier_refreshed"
const MODIFIER_EXPIRED: String = "modifier_expired"
const PICKUP_SPAWN: String = "pickup_spawn"
const PICKUP_ATTRACT: String = "pickup_attract"
const PICKUP_COLLECT: String = "pickup_collect"
const HAZARD_TELEGRAPH: String = "hazard_telegraph"
const HAZARD_ACTIVATED: String = "hazard_activated"
const UI_ENTER: String = "ui_enter"
const UI_EXIT: String = "ui_exit"
const UI_FOCUS: String = "ui_focus"
const UI_PRESS: String = "ui_press"
const UI_SUCCESS: String = "ui_success"
const UI_FAILURE: String = "ui_failure"
const UI_VALUE_INCREASE: String = "ui_value_increase"
const UI_VALUE_DECREASE: String = "ui_value_decrease"
