# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name VfxSpaces

const VALUES: Array[String] = [
	"attached",
	"world",
	"ground",
	"screen",
	"ui",
]

const ATTACHED: String = "attached"
const WORLD: String = "world"
const GROUND: String = "ground"
const SCREEN: String = "screen"
const UI: String = "ui"
