# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name VfxMotionPolicies

const VALUES: Array[String] = [
	"same",
	"variant",
	"suppress_optional",
]

const SAME: String = "same"
const VARIANT: String = "variant"
const SUPPRESS_OPTIONAL: String = "suppress_optional"
