# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name VfxQualities

const VALUES: Array[String] = [
	"low",
	"medium",
	"high",
]

const LOW: String = "low"
const MEDIUM: String = "medium"
const HIGH: String = "high"
