# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name VfxLifecycles

const VALUES: Array[String] = [
	"one_shot",
	"loop",
	"state",
]

const ONE_SHOT: String = "one_shot"
const LOOP: String = "loop"
const STATE: String = "state"
