# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name WorldEventIds

const VALUES: Array[String] = [
	"world_event_defense",
	"world_event_survival",
	"world_event_capture",
	"world_event_gold_shrine",
	"world_event_blood_shrine",
]

const WORLD_EVENT_DEFENSE: String = "world_event_defense"
const WORLD_EVENT_SURVIVAL: String = "world_event_survival"
const WORLD_EVENT_CAPTURE: String = "world_event_capture"
const WORLD_EVENT_GOLD_SHRINE: String = "world_event_gold_shrine"
const WORLD_EVENT_BLOOD_SHRINE: String = "world_event_blood_shrine"
