# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name WorldEventStates

const VALUES: Array[String] = [
	"world_event_state_inactive",
	"world_event_state_active",
	"world_event_state_succeeded",
	"world_event_state_failed",
	"world_event_state_exhausted",
]

const WORLD_EVENT_STATE_INACTIVE: String = "world_event_state_inactive"
const WORLD_EVENT_STATE_ACTIVE: String = "world_event_state_active"
const WORLD_EVENT_STATE_SUCCEEDED: String = "world_event_state_succeeded"
const WORLD_EVENT_STATE_FAILED: String = "world_event_state_failed"
const WORLD_EVENT_STATE_EXHAUSTED: String = "world_event_state_exhausted"
