# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name WorldEventKinds

const VALUES: Array[String] = [
	"world_event_kind_defense",
	"world_event_kind_survival",
	"world_event_kind_capture",
	"world_event_kind_gold_shrine",
	"world_event_kind_blood_shrine",
]

const WORLD_EVENT_KIND_DEFENSE: String = "world_event_kind_defense"
const WORLD_EVENT_KIND_SURVIVAL: String = "world_event_kind_survival"
const WORLD_EVENT_KIND_CAPTURE: String = "world_event_kind_capture"
const WORLD_EVENT_KIND_GOLD_SHRINE: String = "world_event_kind_gold_shrine"
const WORLD_EVENT_KIND_BLOOD_SHRINE: String = "world_event_kind_blood_shrine"
