# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name WorldEventModPoolIds

const VALUES: Array[String] = [
	"world_event_mod_pool_common",
]

const WORLD_EVENT_MOD_POOL_COMMON: String = "world_event_mod_pool_common"
