# This file is generated by tools/sync_contracts.py. Do not edit by hand.
class_name WorldEventRewardTypes

const VALUES: Array[String] = [
	"world_event_reward_gold",
	"world_event_reward_gear_mod",
]

const WORLD_EVENT_REWARD_GOLD: String = "world_event_reward_gold"
const WORLD_EVENT_REWARD_GEAR_MOD: String = "world_event_reward_gear_mod"
