#!/usr/bin/env python3
"""Generate contract artifacts from docs/词表与契约.md."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CONTRACT_DOC = ROOT / "docs" / "词表与契约.md"
CONTRACTS_JSON = ROOT / "client" / "data" / "_contracts.json"
CONTRACTS_DIR = ROOT / "client" / "scripts" / "contracts"
GENERATED_HEADER = "# This file is generated by tools/sync_contracts.py. Do not edit by hand."


@dataclass(frozen=True)
class ContractSection:
    key: str
    heading: str
    output_file: str | None = None
    class_name: str | None = None
    constant_array: str = "VALUES"
    prefix_values: bool = False


SECTIONS: tuple[ContractSection, ...] = (
    ContractSection("stats", "## 1. 属性 stat", "stats.gd", "Stats"),
    ContractSection("effects", "## 2. 效果原语 effect", "effects.gd", "Effects"),
    ContractSection("events", "## 3. 行为事件 behavior.event", "events.gd", "Events"),
    ContractSection("analytics_events", "## 4. 埋点事件 analytics event", "analytics_events.gd", "AnalyticsEvents"),
    ContractSection("settings_keys", "## 5. 设置 key", "settings_keys.gd", "SettingsKeys"),
    ContractSection("actions", "## 7. 输入动作 action", "actions.gd", "Actions"),
    ContractSection("input_binding_ids", "### 7.1 重绑定 binding id", "input_binding_ids.gd", "InputBindingIds"),
    ContractSection("pool_ids", "## 8. 对象池 id", "pool_ids.gd", "PoolIds"),
    ContractSection(
        "gold_transaction_reasons",
        "## 8-A. 金币交易原因 gold_transaction_reason",
        "gold_transaction_reasons.gd",
        "GoldTransactionReasons",
    ),
    ContractSection(
        "reward_choice_triggers",
        "## 8-B. 奖励选择触发 reward_choice_trigger",
        "reward_choice_triggers.gd",
        "RewardChoiceTriggers",
    ),
    ContractSection("elements", "## 9. 战斗元素 element_id", "elements.gd", "Elements"),
    ContractSection("status_effects", "## 9-A. 状态效果 status_effect", "status_effects.gd", "StatusEffects"),
    ContractSection("status_stack_rules", "## 9-B. 状态叠加规则 status_stack_rule", "status_stack_rules.gd", "StatusStackRules"),
    ContractSection(
        "damage_target_groups",
        "## 17-F. 伤害目标组 damage_target_group",
        "damage_target_groups.gd",
        "DamageTargetGroups",
    ),
    ContractSection("audio_prefixes", "## 10. 音频 id audio_id", "audio_ids.gd", "AudioIds", "PREFIXES", True),
    ContractSection("rng_streams", "## 11. RNG 子流 rng_stream", "rng_streams.gd", "RngStreams"),
    ContractSection("character_ids", "### 12.1 角色 id character_id", "character_ids.gd", "CharacterIds"),
    ContractSection("capabilities", "### 12.2 能力 capability_id", "capabilities.gd", "Capabilities"),
    ContractSection("content_tags", "### 12.3 内容标签 content_tag", "content_tags.gd", "ContentTags"),
    ContractSection("game_modes", "## 12-A. 游戏模式 id game_mode", "game_modes.gd", "GameModes"),
    ContractSection("enemy_ai_actions", "## 12-B. 敌人 AI 动作 enemy_ai_action", "enemy_ai_actions.gd", "EnemyAiActions"),
    ContractSection(
        "enemy_defeat_causes",
        "## 12-B1. 敌人退场原因 enemy_defeat_cause",
        "enemy_defeat_causes.gd",
        "EnemyDefeatCauses",
    ),
    ContractSection("skill_ids", "## 12-C. 技能 id skill_id", "skill_ids.gd", "SkillIds"),
    ContractSection("skill_resources", "## 12-D. 技能资源 skill_resource", "skill_resources.gd", "SkillResources"),
    ContractSection("skill_targeting", "## 12-E. 技能目标选择 skill_targeting", "skill_targeting.gd", "SkillTargeting"),
    ContractSection("skill_effects", "## 12-F. 技能效果 skill_effect", "skill_effects.gd", "SkillEffects"),
    ContractSection("ability_tags", "## 12-G. 能力标签 ability_tag", "ability_tags.gd", "AbilityTags"),
    ContractSection("skill_slots", "## 12-H. 技能槽位 skill_slot", "skill_slots.gd", "SkillSlots"),
    ContractSection("hero_passive_ids", "## 12-I. 英雄被动 id hero_passive_id", "hero_passive_ids.gd", "HeroPassiveIds"),
    ContractSection("gear_mod_ids", "## 13-A. 装备 Mod id gear_mod_id", "gear_mod_ids.gd", "GearModIds"),
    ContractSection("gear_mod_slots", "## 13-B. 装备 Mod 槽位 gear_mod_slot", "gear_mod_slots.gd", "GearModSlots"),
    ContractSection("gear_mod_rarities", "## 13-C. 装备 Mod 稀有度 gear_mod_rarity", "gear_mod_rarities.gd", "GearModRarities"),
    ContractSection("gear_mod_kinds", "## 13-D. 装备 Mod 种类 gear_mod_kind", "gear_mod_kinds.gd", "GearModKinds"),
    ContractSection("gear_mod_map_behaviors", "## 13-E. 地图 Mod 行为 gear_mod_map_behavior", "gear_mod_map_behaviors.gd", "GearModMapBehaviors"),
    ContractSection("gear_mod_grid_behaviors", "## 13-F. 格子 Mod 行为 gear_mod_grid_behavior", "gear_mod_grid_behaviors.gd", "GearModGridBehaviors"),
    ContractSection("gear_mod_placement_outcomes", "## 13-G. Gear Mod 放置结果 gear_mod_placement_outcome", "gear_mod_placement_outcomes.gd", "GearModPlacementOutcomes"),
    ContractSection("save_kinds", "## 14. 存档种类 save_kind", "save_kinds.gd", "SaveKinds"),
    ContractSection("module_roles", "## 15-A. 模块角色 module_role", "module_roles.gd", "ModuleRoles"),
    ContractSection("module_cell_tokens", "## 15-B. 模块格子令牌 module_cell_token", "module_cell_tokens.gd", "ModuleCellTokens"),
    ContractSection("module_placement_types", "## 15-C. 模块摆放原语 module_placement_type", "module_placement_types.gd", "ModulePlacementTypes"),
    ContractSection("module_edge_directions", "## 15-D. 模块边缘方向 module_edge_direction", "module_edge_directions.gd", "ModuleEdgeDirections"),
    ContractSection("module_review_statuses", "## 15-E. 模块审核状态 module_review_status", "module_review_statuses.gd", "ModuleReviewStatuses"),
    ContractSection("module_tile_ids", "## 15-F. 模块图块 module_tile_id", "module_tile_ids.gd", "ModuleTileIds"),
    ContractSection(
        "world_event_ids",
        "## 17-A. 世界事件 id world_event_id",
        "world_event_ids.gd",
        "WorldEventIds",
    ),
    ContractSection(
        "world_event_kinds",
        "## 17-B. 世界事件类型 world_event_kind",
        "world_event_kinds.gd",
        "WorldEventKinds",
    ),
    ContractSection(
        "world_event_states",
        "## 17-C. 世界事件状态 world_event_state",
        "world_event_states.gd",
        "WorldEventStates",
    ),
    ContractSection(
        "world_event_reward_types",
        "## 17-D. 世界事件奖励类型 world_event_reward_type",
        "world_event_reward_types.gd",
        "WorldEventRewardTypes",
    ),
    ContractSection(
        "world_event_mod_pool_ids",
        "## 17-E. 世界事件 Gear Mod 池 world_event_mod_pool_id",
        "world_event_mod_pool_ids.gd",
        "WorldEventModPoolIds",
    ),
    ContractSection("vfx_domains", "## 16-A. 视觉效果领域 vfx_domain", "vfx_domains.gd", "VfxDomains"),
    ContractSection("vfx_kinds", "## 16-B. 视觉效果执行种类 vfx_kind", "vfx_kinds.gd", "VfxKinds"),
    ContractSection("vfx_spaces", "## 16-C. 视觉效果空间 vfx_space", "vfx_spaces.gd", "VfxSpaces"),
    ContractSection("vfx_lifecycles", "## 16-D. 视觉效果生命周期 vfx_lifecycle", "vfx_lifecycles.gd", "VfxLifecycles"),
    ContractSection("vfx_cues", "## 16-E. 视觉表现 cue vfx_cue", "vfx_cues.gd", "VfxCues"),
    ContractSection("vfx_anchors", "## 16-F. 视觉效果挂点 vfx_anchor", "vfx_anchors.gd", "VfxAnchors"),
    ContractSection(
        "content_unlock_types",
        "## 18-A. 可解锁内容类型 content_unlock_type",
        "content_unlock_types.gd",
        "ContentUnlockTypes",
    ),
    ContractSection(
        "content_unlock_rule_modes",
        "## 18-B. 解锁规则组合模式 content_unlock_rule_mode",
        "content_unlock_rule_modes.gd",
        "ContentUnlockRuleModes",
    ),
    ContractSection(
        "content_unlock_progress_counters",
        "## 18-C. 解锁进度计数器 content_unlock_progress_counter",
        "content_unlock_progress_counters.gd",
        "ContentUnlockProgressCounters",
    ),
)

LOCALE_PREFIXES_HEADING = "## 6. 本地化 key 命名规范"
RESERVED_CONSTANT_NAMES = {"TRUE", "FALSE", "NULL", "NAN", "INF"}
CONTENT_REGISTRATION_PREFIXES: dict[str, str] = {
    "character_ids": "character_",
    "game_modes": "mode_",
    "skill_ids": "skill_",
    "hero_passive_ids": "passive_",
    "gear_mod_ids": "gear_mod_",
    "world_event_ids": "world_event_",
}
CONTENT_ID_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate contract JSON and GDScript constants.")
    actions = parser.add_mutually_exclusive_group()
    actions.add_argument("--check", action="store_true", help="Fail if generated artifacts are out of date.")
    actions.add_argument(
        "--register",
        nargs=2,
        metavar=("CONTRACT_KEY", "ID"),
        help="Register an allowlisted content id and regenerate artifacts.",
    )
    actions.add_argument(
        "--unregister",
        nargs=2,
        metavar=("CONTRACT_KEY", "ID"),
        help="Unregister an allowlisted content id and regenerate artifacts.",
    )
    parser.add_argument("--meaning", default=None, help="Required human-readable meaning for --register.")
    parser.add_argument("--dry-run", action="store_true", help="Validate and preview without writing files.")
    args = parser.parse_args()

    try:
        contract_text = _read_contract_doc()
        mutation_summary = ""
        if args.register:
            if args.meaning is None or not args.meaning.strip():
                raise ContractError("--register requires a non-empty --meaning")
            contract_key, content_id = args.register
            contract_text = mutate_contract_document(
                contract_text,
                "register",
                contract_key,
                content_id,
                args.meaning,
            )
            mutation_summary = f"register {contract_key} {content_id}"
        elif args.unregister:
            if args.meaning is not None:
                raise ContractError("--meaning is only valid with --register")
            contract_key, content_id = args.unregister
            contract_text = mutate_contract_document(
                contract_text,
                "unregister",
                contract_key,
                content_id,
            )
            mutation_summary = f"unregister {contract_key} {content_id}"
        elif args.meaning is not None:
            raise ContractError("--meaning requires --register")
        artifacts = build_artifacts(contract_text)
    except ContractError as exc:
        print(f"[sync-contracts] {exc}")
        return 1

    if args.check:
        return _check_artifacts(artifacts)

    if args.dry_run:
        if mutation_summary:
            print(f"[sync-contracts] dry-run: {mutation_summary}")
        else:
            print("[sync-contracts] dry-run: generated artifacts are valid")
        return 0

    if mutation_summary:
        artifacts = {CONTRACT_DOC: contract_text, **artifacts}
    _write_artifacts(artifacts)
    print("sync contracts passed")
    return 0


class ContractError(RuntimeError):
    pass


def extract_contracts(text: str | None = None) -> dict[str, list[str]]:
    if text is None:
        text = _read_contract_doc()
    contracts: dict[str, list[str]] = {}

    for section in SECTIONS:
        section_text = _section_text(text, section.heading)
        values = _extract_first_column_ids(section_text, prefix_values=section.prefix_values)
        contracts[section.key] = values

    contracts["locale_prefixes"] = _extract_locale_prefixes(_section_text(text, LOCALE_PREFIXES_HEADING))
    return contracts


def build_artifacts(text: str | None = None) -> dict[Path, str]:
    contracts = extract_contracts(text)
    payload = {
        "schema_version": 1,
        "source": "docs/词表与契约.md",
        "generated_by": "tools/sync_contracts.py",
        "contracts": contracts,
    }

    artifacts: dict[Path, str] = {
        CONTRACTS_JSON: json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
    }

    for section in SECTIONS:
        if section.output_file is None or section.class_name is None:
            continue
        artifacts[CONTRACTS_DIR / section.output_file] = _render_gd_constants(
            section.class_name,
            section.constant_array,
            contracts[section.key],
            prefix_constants=section.prefix_values,
        )

    return artifacts


def mutate_contract_document(
    text: str,
    action: str,
    contract_key: str,
    content_id: str,
    meaning: str = "",
) -> str:
    section = next((item for item in SECTIONS if item.key == contract_key), None)
    if section is None or contract_key not in CONTENT_REGISTRATION_PREFIXES:
        allowed = ", ".join(sorted(CONTENT_REGISTRATION_PREFIXES))
        raise ContractError(f"contract key is not content-registerable: {contract_key}; allowed: {allowed}")
    prefix = CONTENT_REGISTRATION_PREFIXES[contract_key]
    if not CONTENT_ID_RE.fullmatch(content_id) or not content_id.startswith(prefix):
        raise ContractError(f"invalid {contract_key} id: {content_id}; expected prefix {prefix}")
    if action not in {"register", "unregister"}:
        raise ContractError(f"unsupported contract mutation: {action}")

    section_start = text.find(section.heading)
    if section_start < 0:
        raise ContractError(f"missing heading: {section.heading}")
    next_heading = re.search(r"\n#{2,3} ", text[section_start + 1 :])
    section_end = len(text) if next_heading is None else section_start + 1 + next_heading.start()
    section_text = text[section_start:section_end]
    row_pattern = re.compile(
        rf"^\|\s*`{re.escape(content_id)}`\s*\|[^\r\n]*(?:\r?\n|$)",
        re.MULTILINE,
    )
    existing = row_pattern.search(section_text)
    if action == "unregister":
        if existing is None:
            raise ContractError(f"contract id is not registered: {contract_key} {content_id}")
        updated_section = section_text[: existing.start()] + section_text[existing.end() :]
        return text[:section_start] + updated_section + text[section_end:]

    if existing is not None:
        raise ContractError(f"contract id is already registered: {contract_key} {content_id}")
    clean_meaning = meaning.strip()
    if any(character in clean_meaning for character in ("\n", "\r", "|", "`")):
        raise ContractError("contract meaning cannot contain newline, pipe, or backtick")
    table_rows = list(re.finditer(r"^\|[^\r\n]*\|[ \t]*$", section_text, re.MULTILINE))
    if len(table_rows) < 2:
        raise ContractError(f"contract section has no writable table: {contract_key}")
    insert_at = table_rows[-1].end()
    new_row = f"\n| `{content_id}` | {clean_meaning} |"
    updated_section = section_text[:insert_at] + new_row + section_text[insert_at:]
    return text[:section_start] + updated_section + text[section_end:]


def _read_contract_doc() -> str:
    if not CONTRACT_DOC.exists():
        raise ContractError("missing docs/词表与契约.md")
    return CONTRACT_DOC.read_text(encoding="utf-8")


def _section_text(text: str, heading: str) -> str:
    start = text.find(heading)
    if start < 0:
        raise ContractError(f"missing heading: {heading}")
    next_heading = re.search(r"\n#{2,3} ", text[start + 1 :])
    if next_heading is None:
        return text[start:]
    return text[start : start + 1 + next_heading.start()]


def _extract_first_column_ids(section_text: str, *, prefix_values: bool = False) -> list[str]:
    values: list[str] = []
    for line in section_text.splitlines():
        stripped = line.strip()
        if not stripped.startswith("|") or set(stripped.replace("|", "").strip()) <= {"-", ":"}:
            continue
        cells = [cell.strip() for cell in stripped.strip("|").split("|")]
        if not cells or "`" not in cells[0]:
            continue
        for raw in re.findall(r"`([^`]+)`", cells[0]):
            value = _normalize_contract_value(raw, prefix_value=prefix_values)
            if value not in values:
                values.append(value)
    if not values:
        raise ContractError("no contract ids found in section")
    return values


def _extract_locale_prefixes(section_text: str) -> list[str]:
    prefixes: list[str] = []
    for raw in re.findall(r"`([a-z0-9_]+_)`", section_text):
        if raw not in prefixes:
            prefixes.append(raw)
    if not prefixes:
        raise ContractError("no locale prefixes found")
    return prefixes


def _normalize_contract_value(raw: str, *, prefix_value: bool) -> str:
    value = raw.strip()
    if prefix_value and value.endswith("*"):
        value = value[:-1]
    return value


def _render_gd_constants(
    class_name: str,
    array_name: str,
    values: list[str],
    *,
    prefix_constants: bool = False,
) -> str:
    lines = [
        "# This file is generated by tools/sync_contracts.py. Do not edit by hand.",
        f"class_name {class_name}",
        "",
        f"const {array_name}: Array[String] = [",
    ]
    for value in values:
        lines.append(f'\t"{value}",')
    lines.extend(["]", ""])

    for value in values:
        constant_name = _constant_name(value, suffix="PREFIX" if prefix_constants else "")
        lines.append(f'const {constant_name}: String = "{value}"')

    return "\n".join(lines) + "\n"


def _constant_name(value: str, *, suffix: str = "") -> str:
    base = value.rstrip("_").replace(".", "_").replace("/", "_")
    base = re.sub(r"[^A-Za-z0-9]+", "_", base).strip("_").upper()
    if suffix:
        base = f"{base}_{suffix}"
    if base in RESERVED_CONSTANT_NAMES or not base:
        base = f"ID_{base}"
    return base


def _write_artifacts(artifacts: dict[Path, str]) -> None:
    backups: dict[Path, bytes | None] = {}
    temp_paths: list[Path] = []
    stale_paths = _stale_generated_artifacts(set(artifacts))
    try:
        for path, content in artifacts.items():
            backups[path] = path.read_bytes() if path.exists() else None
            path.parent.mkdir(parents=True, exist_ok=True)
            temp_path = path.with_name(f".{path.name}.sync-contracts.tmp")
            temp_path.write_text(content, encoding="utf-8", newline="\n")
            temp_paths.append(temp_path)
        for path in artifacts:
            temp_path = path.with_name(f".{path.name}.sync-contracts.tmp")
            os.replace(temp_path, path)
        for stale_path in stale_paths:
            backups[stale_path] = stale_path.read_bytes()
            stale_path.unlink()
            uid_path = Path(f"{stale_path}.uid")
            if uid_path.exists():
                backups[uid_path] = uid_path.read_bytes()
                uid_path.unlink()
    except OSError as exc:
        for path, content in backups.items():
            try:
                if content is None:
                    path.unlink(missing_ok=True)
                else:
                    restore_path = path.with_name(f".{path.name}.sync-contracts.restore")
                    restore_path.write_bytes(content)
                    os.replace(restore_path, path)
            except OSError:
                pass
        raise ContractError(f"failed to write contract transaction: {exc}") from exc
    finally:
        for temp_path in temp_paths:
            temp_path.unlink(missing_ok=True)


def _check_artifacts(artifacts: dict[Path, str]) -> int:
    errors: list[str] = []
    for path, expected in artifacts.items():
        if not path.exists():
            errors.append(f"missing generated artifact: {_rel(path)}")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            errors.append(f"outdated generated artifact: {_rel(path)}")
    for path in _stale_generated_artifacts(set(artifacts)):
        errors.append(f"stale generated artifact: {_rel(path)}")

    if errors:
        for error in errors:
            print(f"[sync-contracts] {error}")
        print("[sync-contracts] run: python tools/sync_contracts.py")
        return 1

    print("sync contracts check passed")
    return 0


def _stale_generated_artifacts(expected_paths: set[Path]) -> list[Path]:
    stale: list[Path] = []
    for path in CONTRACTS_DIR.glob("*.gd"):
        if path in expected_paths:
            continue
        try:
            first_line = path.read_text(encoding="utf-8").splitlines()[0]
        except (OSError, IndexError, UnicodeDecodeError):
            continue
        if first_line == GENERATED_HEADER:
            stale.append(path)
    return sorted(stale)


def _remove_stale_generated_artifacts(expected_paths: set[Path]) -> None:
    for path in _stale_generated_artifacts(expected_paths):
        path.unlink()
        uid_path = Path(f"{path}.uid")
        if uid_path.exists():
            uid_path.unlink()


def _rel(path: Path) -> str:
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


if __name__ == "__main__":
    sys.exit(main())
